import logo from "../assets/imgs/png/logo.png";
import leaf from "../assets/imgs/jpg/leaf.jpg";
import crops from "../assets/imgs/jpg/crops.jpg";
import marketcrop from "../assets/imgs/jpg/marketcrop.jpg";
import eco from "../assets/imgs/png/eco.png";
import fresh from "../assets/imgs/png/fresh.png";
import safe from "../assets/imgs/png/safe.png";
import easy from "../assets/imgs/png/easy.png";
import fertilizer from "../assets/imgs/png/fertilizer.png";
import weather from "../assets/imgs/png/weather.png";
import plantdisease from "../assets/imgs/png/plantdisease.png";
import market from "../assets/imgs/png/market.png";
import Yield from "../assets/imgs/png/yield.png";
import pottasium from "../assets/imgs/png/pottasium.png";
import phosphorous from "../assets/imgs/png/phosphorous.png";
import raining from "../assets/imgs/png/raining.png";
import ph from "../assets/imgs/png/ph.png";
import nitrogen from "../assets/imgs/png/nitrogen.png";
import askquestionImg from "../assets/imgs/png/askQuestion.png";
import consultationImg from "../assets/imgs/png/consultation.png";
import stampImg from "../assets/imgs/png/stamp.png";
import CommunityImg from "../assets/imgs/png/community.png";

// IMAGES

export const Applogo = logo;
export const leafimg = leaf;
export const ecoimage = eco;
export const freshimage = fresh;
export const safeimage = safe;
export const easyimage = easy;
export const cropsimage = crops;
export const yieldimage = Yield;
export const marketimg = market;
export const plantdiseaseimg = plantdisease;
export const weatherimg = weather;
export const fertilizerimg = fertilizer;
export const MarketCropsImg = marketcrop;
export const ConsultImage = consultationImg;
export const askquestionImage = askquestionImg;
export const PhImg = ph;
export const NitrogenImg = nitrogen;
export const RainingImg = raining;
export const PhosphorousImg = phosphorous;
export const PottasiumImg = pottasium;
export const stampImage = stampImg;
export const CommunityImage = CommunityImg;
// ICONS

import { IoMdClose } from "react-icons/io";
import { CiMenuFries, CiCloudDrizzle } from "react-icons/ci";
import { FaStar } from "react-icons/fa";
import { FaArrowRightLong } from "react-icons/fa6";
import { GiInsectJaws, GiFarmer } from "react-icons/gi";
import { GoGraph } from "react-icons/go";
import { IoEyeOutline } from "react-icons/io5";
import { FaGithub } from "react-icons/fa";
import { CiCloud } from "react-icons/ci";
import { CiTempHigh } from "react-icons/ci";
import { PiWindThin } from "react-icons/pi";
import { WiHumidity } from "react-icons/wi";
import { BsCloudRain } from "react-icons/bs";
import { GiFertilizerBag } from "react-icons/gi";
import { PiGrains } from "react-icons/pi";
import { CgTrees } from "react-icons/cg";
import { CgCommunity } from "react-icons/cg";
import { MdCastForEducation } from "react-icons/md";
import { IoIosCall } from "react-icons/io";
import { CiHome } from "react-icons/ci";
import { RxAvatar } from "react-icons/rx";
import { MdOutlineContactless } from "react-icons/md";
import { FaRegAddressBook } from "react-icons/fa";
import { MdAlternateEmail } from "react-icons/md";
import { IoInformationCircleOutline } from "react-icons/io5";

export const Menucloseicon = IoMdClose;
export const Menuopen = CiMenuFries;
export const Rightarrowicon = FaArrowRightLong;
export const Staricon = FaStar;
export const Framericon = GiFarmer;
export const Insectsicon = GiInsectJaws;
export const Graphicon = GoGraph;
export const Cloudicon = CiCloudDrizzle;
export const Passwordeye = IoEyeOutline;
export const GithubIcon = FaGithub;
export const CloudIcon = CiCloud;
export const RainyCloudIcon = CiCloudDrizzle;
export const TempIcon = CiTempHigh;
export const WindIcon = PiWindThin;
export const HumidityIcon = WiHumidity;
export const RainIcon = BsCloudRain;
export const FertlizerIcon = GiFertilizerBag;
export const GrainsIcon = PiGrains;
export const CgTreesIcons = CgTrees;
export const CommunityIcons = CgCommunity;
export const EducationIcon = MdCastForEducation;
export const HomeIcon = CiHome;
export const ContactIcon = MdOutlineContactless;
export const ProfileIcon = RxAvatar;
export const CallIcon = IoIosCall;
export const EmailIcon = MdAlternateEmail;
export const AddressIcon = FaRegAddressBook;
export const InfoIcon = IoInformationCircleOutline;
